### ISSUE TITLE
Problem with REST target

### ISSUE THREAD

**Issue by giuseppelasco17** [IBA-Group-IT/IoT-data-simulator#13]
I create a server flask that receive GET and POST on a certain port. From the browser it works, but if I set the target of the session of IoT-data-simulator to server URL I receive this kind of error "Error: connect ECONNREFUSED 127.0.0.1:8001".

**Comment by vadzim-kazak** [comment]
Hi, could you please try to specify you host machine IP address instead of localhost or 127.0.0.1 in target system url? Data simulator runs in containers, so localhost or 127.0.0.1 is treated as container self address instead of host machine.

**Comment by giuseppelasco17** [comment]
You're completely right, I wasn't thinking about the fact that IoT-data-simulator is on Docker.
Sorry for the stupid question :sweat_smile:
