### ISSUE TITLE
getting attached build error

### ISSUE THREAD

**Issue by reddy003** [IBA-Group-IT/IoT-data-simulator#8]
---> Running in e8bb6b388c21
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/25) Installing ncurses-terminfo-base (6.0_p20171125-r0)
(2/25) Installing ncurses-terminfo (6.0_p20171125-r0)
ERROR: ncurses-terminfo-6.0_p20171125-r0: Protocol error
(3/25) Installing ncurses-libs (6.0_p20171125-r0)
(4/25) Installing readline (6.3.008-r5)
(5/25) Installing bash (4.3.48-r1)
(6/25) Installing binutils-libs (2.30-r1)
ERROR: bash-4.3.48-r1: Protocol error
(7/25) Installing binutils (2.30-r1)
(8/25) Installing gmp (6.1.2-r0)
(9/25) Installing isl (0.17.1-r0)
(10/25) Installing libgomp (6.3.0-r4)
(11/25) Installing libatomic (6.3.0-r4)

ERROR: libatomic-6.3.0-r4: temporary error (try again later)
(12/25) Installing pkgconf (1.3.7-r0)
(13/25) Installing mpfr3 (3.1.5-r0)
ERROR: mpfr3-3.1.5-r0: Protocol error
(14/25) Installing mpc1 (1.0.3-r0)
(15/25) Installing gcc (6.3.0-r4)
ERROR: gcc-6.3.0-r4: Protocol error
(16/25) Installing musl-dev (1.1.16-r14)
(17/25) Installing libc-dev (0.7.1-r0)
(18/25) Installing g++ (6.3.0-r4)
ERROR: (19/25) Installing make (4.2.1-r0)
g++-6.3.0-r4: Protocol error
(20/25) Installing libbz2 (1.0.6-r5)
(21/25) Installing expat (2.2.0-r1)
(22/25) Installing libffi (3.2.1-r3)
ERROR: libffi-3.2.1-r3: Protocol error
(23/25) Installing gdbm (1.12-r0)
(24/25) Installing sqlite-libs (3.20.1-r2)
ERROR: sqlite-libs-3.20.1-r2: Protocol error
(25/25) Installing python2 (2.7.14-r0)
Executing busybox-1.26.2-r9.trigger
8 errors; 68 MiB in 30 packages
ERROR: Service 'data-sender' failed to build: The command '/bin/sh -c apk add --no-cache make gcc g++ python bash' returned a non-zero code: 8

**Comment by vadzim-kazak** [comment]
hi @reddy003. 
I managed to build data-sender image this morning using the following command 
`docker-compose build --no-cache data-sender`
Could you please provide more details regarding your dev environment? (OS, docker version)

**Comment by vadzim-kazak** [comment]
hi @reddy003. Any progress?

**Comment by vadzim-kazak** [comment]
Closed as non reproducible
